### PR TITLE
Create Drivetrain_newest

### PR DESCRIPTION
**Pull request by mergd**
Commit?
Test b4 anyting
i can change programming based upon driving styles
thx,
wx

### CODE REVIEW

**Comment by adyoungblood** [comment]
It seems a bit unwieldy; why not use the bumpers and triggers and just set the motor power to the triggers' value, and make the bumpers move it backwards? Or use the joysticks?

**Comment by mergd** [comment]
Good idea- 
Didn't we already decide that the front 4 buttons on the controller front would be the driving mechanism?

**Comment by mergd** [comment]
BTW, this is my 1st program 4 the team

**Comment by mergd** [comment]
Sensor values can't be negative; so going backwards isn't an option with the motor power being equal to the trigger value

**Comment by adyoungblood** [comment]
We can use the bumpers above the triggers to either go backwards, or for more control, simply make the trigger values negative while held down. The system you made is very good for your first program, so don't feel bad.

**Comment by mergd** [comment]
good idea - i'll do that

**Pull request merged**
